image: "registry.gitlab.com/obruns/demonstrate-merge-strategies/debian-build:2.0"

variables:
    BOOST_TEST_COLOR_OUTPUT: 1
    BOOST_TEST_LOG_LEVEL: "unit_scope"
    BUILD_ON_TRAVIS: 1
    NINJA_STATUS: "[%r %c %o %e (%s/%t)]"

before_script:
    - g++ --version
    - clang++ --version
    - cmake --version
    - ninja --version

.builder_template: &build_definition
    script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$MODE
        - time timeout 1200 ninja -v
        - time timeout 10 ctest --verbose

clang-format:
    script:
        - git diff -U0 --no-color "origin/master..HEAD" | /usr/share/clang/clang-format-7/clang-format-diff.py -p1 | sh -c 'IFS=$'\n' ; exitCode=0 ; while read -r line ; do if [ ! -z "${line}" ] ; then exitCode=1 ; color=""; echo ${line} | grep "^- " > /dev/null ; if [ $? -eq 0 ] ; then color="\033[0;31m" ; fi ; echo ${line} | grep "^+ " > /dev/null ; if [ $? -eq 0 ] ; then color="\033[0;32m" ; fi ; printf "%b%s%s\033[0m\n" ${color} ${line} ; fi ; done ; exit ${exitCode}'

clang-tidy:
    script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_CXX_CLANG_TIDY:STRING='clang-tidy' -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
        - time timeout 1200 ninja -v

clang-debug:
    <<: *build_definition
    variables:
        COMPILER: clang++
        MODE: Debug

clang-release:
    <<: *build_definition
    variables:
        COMPILER: clang++
        MODE: Release

gcc-debug:
    <<: *build_definition
    variables:
        COMPILER: g++
        MODE: Debug

gcc-release:
    <<: *build_definition
    variables:
        COMPILER: g++
        MODE: Release
