image: "registry.gitlab.com/obruns/demonstrate-merge-strategies/debian-build:1.0"

variables:
    BOOST_TEST_COLOR_OUTPUT: 1
    BOOST_TEST_LOG_LEVEL: "unit_scope"
    BUILD_ON_TRAVIS: 1
    NINJA_STATUS: "[%r %c %o %e (%s/%t)]"

before_script:
    - g++ --version
    - clang++ --version
    - cmake --version
    - ninja --version

.builder_template: &build_definition
    script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$MODE
        - time timeout 1200 ninja -v
        - time timeout 10 ctest --verbose

clang-tidy:
    script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_CXX_CLANG_TIDY:STRING='clang-tidy' -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
        - time timeout 1200 ninja -v

clang-debug:
    <<: *build_definition
    variables:
        COMPILER: clang++
        MODE: Debug

clang-release:
    <<: *build_definition
    variables:
        COMPILER: clang++
        MODE: Release

gcc-debug:
    <<: *build_definition
    variables:
        COMPILER: g++
        MODE: Debug

gcc-release:
    <<: *build_definition
    variables:
        COMPILER: g++
        MODE: Release
